lc_caisse_home:
    path:     /{max}
    defaults: { _controller: LogiCorpoBundle:Caisse:index, max: 20 }

lc_caisse_transaction_nouvelle:
    path:     /transaction/new
    defaults: { _controller: LogiCorpoBundle:Caisse:nouvelleTransaction}

lc_caisse_transaction_corriger:
    path:     /transaction/correct/{id}
    defaults: { _controller: LogiCorpoBundle:Caisse:corriger}
    requirements:
        id: \d+

lc_caisse_transaction_chercher:
    path:     /transaction/search
    defaults: { _controller: LogiCorpoBundle:Caisse:chercher}

lc_caisse_soldes_period:
    path: /soldes/{from}/{step}
    defaults: { _controller: LogiCorpoBundle:Caisse:jsonSoldesPeriod, step: '1D' }