lc_produit_home:
    path:     /
    defaults: { _controller: LogiCorpoBundle:Produit:index }

lc_produit_new:
    path:     /nouveau
    defaults: { _controller: LogiCorpoBundle:Produit:nouveau }

lc_produit_list:
    path:     /list
    defaults: { _controller: LogiCorpoBundle:Produit:jsonList }