lc_compte_home:
    path:     /
    defaults: { _controller: LogiCorpoBundle:Compte:index, limite: 25 }

lc_compte_mdp:
    path:     /edit-mdp
    defaults: { _controller: LogiCorpoBundle:Security:changePass }

lc_compte_upgrade:
    path:     /upgrade
    defaults: { _controller: LogiCorpoBundle:Utilisateur:upgrade, redirection: lc_compte_home, moyenPaiement: compte, user: null }