lc_homepage:
    path:     /
    defaults: { _controller: LogiCorpoBundle:Compte:index }

lc_utilisateur:
    resource: "@LogiCorpoBundle/Resources/config/routing_utilisateur.yml"
    prefix:   /utilisateur

lc_produit:
    resource: "@LogiCorpoBundle/Resources/config/routing_produit.yml"
    prefix:   /produit

lc_commande:
    resource: "@LogiCorpoBundle/Resources/config/routing_commande.yml"
    prefix:   /commande

lc_service:
    resource: "@LogiCorpoBundle/Resources/config/routing_service.yml"
    prefix:   /service

lc_compte:
    resource: "@LogiCorpoBundle/Resources/config/routing_compte.yml"
    prefix:   /compte

lc_caisse:
    resource: "@LogiCorpoBundle/Resources/config/routing_caisse.yml"
    prefix:   /caisse

lc_parametre:
    resource: "@LogiCorpoBundle/Resources/config/routing_parametre.yml"
    prefix:   /parametre

login:
    path:   /login
    defaults:  { _controller: LogiCorpoBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout