services:
    security.authentication.success:
        class:  LogiCorpoBundle\Listeners\LoginSuccessHandler
        arguments: ['@doctrine.orm.entity_manager', '@router']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
