services:
    logicorpo.security.authentication_event_listener:
        class: LogiCorpoBundle\Listeners\AuthenticationListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: ['@security.authorization_checker','@doctrine.orm.entity_manager']